### PR TITLE
remove ggforce dependency

### PR DESCRIPTION
**Pull request by dpastoor**
ggforce is actually a pretty huge dependency. On top of that, it that is a blocker for larger organizations with HPC's with older R versions (eg AZ is on 3.2.4).

The ggforce dependency tree ends up introducing system dependencies such as V8 (due to concaveman), R 3.3 (sf) and the list goes on. Given the only need for ggforce is the pagination functions, these can instead be factored out and placed directly in this package to remove the dependency.

This PR lowers the R dependency requirement to below 3.3, and also completely removes the ggforce dep tree.

Rerunning the pagination tests shows all still pass.

### CODE REVIEW

**Comment by mattfidler** [comment]
Novartis also uses 3.2, I think that is would be good to remove ggforce

**Comment by guiastrennec** [comment]
Thanks for the PR @dpastoor. It would indeed be nice to remove as much dependencies as possible while keeping the packages features. However I don't think we can just take code from ggforce and add it to xpose without getting the approval from the author. In ggforce they used GPL >=2 and in xpose we use a less restrictive license LGPL 3.

**Comment by dpastoor** [comment]
@guiastrennec you can 'call' this code LGPL 3 but the fact is that if you have a dependency on code with a more restrictive license, you're "infected" by that license as well.

You can't just say "because the code exists in another repo rather than mine, I am not subject to that license". 

Also note, ggplot2 itself is GPL-2 licensed. Point being - you can put whatever you "want" in the license field, but that is irrelevant, you're already under ggplot/ggforce/etc's license regardless of if its in another repository or directly embedded. We still should link back to saying where the code came from for copyright purposes, but licensing is really a non-discussion as to how to support ggforce-related or other code.

**Comment by dpastoor** [comment]
Feel free to read more

https://softwareengineering.stackexchange.com/questions/342156/can-i-use-some-gpl-code-in-lgpl-project

or even better check out the actual license terms http://www.gnu.org/licenses/gpl-faq.html

as @mattfidler also suggested - this is also something that is really needed in order to even install xpose on larger organization's clusters. 

@mikeksmith what version of R does Pfizer have on its HPC's? 

What I really don't want to see happen is having to manage two separate forks of xpose, which would "need" to happen for people in those groups to use.

**Comment by MikeKSmith** [comment]
Pfizer is moving towards R-3.4.1. Older versions of R remain available but we wouldn’t retrofit xpose to those versions.

On 20 Nov 2017, at 18:24, Devin Pastoor <notifications@github.com<mailto:notifications@github.com>> wrote:


Feel free to read more

https://softwareengineering.stackexchange.com/questions/342156/can-i-use-some-gpl-code-in-lgpl-project

or even better check out the actual license terms http://www.gnu.org/licenses/gpl-faq.html

as @mattfidler<https://github.com/mattfidler> also suggested - this is also something that is really needed in order to even install xpose on larger organization's clusters.

@MikeKSmith<https://github.com/mikeksmith> what version of R does Pfizer have on its HPC's?

What I really don't want to see happen is having to manage two separate forks of xpose, which would "need" to happen for people in those groups to use.

**Comment by dpastoor** [comment]
all said though @guiastrennec if you feel more comfortable (even though "legally" it wouldn't matter) Thomas is quite approachable and I'm sure we can get contributor consent to include these code snippets directly - shall we ping him?

**Comment by guiastrennec** [comment]
Hi Devin thanks for these links I will take some time to look at them. My current understanding was that the GPL-2 license contamination did not applied if you bundled the package, it only applied to its source code this was the reason why we chose LGPL3 for xpose, but I could be wrong. 

License apart, I do think we should discuss this with Thomas before hand.

**Comment by dpastoor** [comment]
@thomasp85 - we're looking to remove the ggforce dependency (see PR info above). Would you mind us including the above code directly from ggforce - with attribution as we only need the facet_paginate functionality, not the entire scope of ggforce?

**Comment by smouksassi** [comment]
Dear All, I think the paging functionality of ggforce  and the "printing" facilities of such multipage ggplot objects from xpose might deserve their own package ?. 
Needless to say that multipage plots can be needed independent from xpose and or ggforce other features.
There is still no easy way in R to generate  equivalent multipage trellis graphics as we used to be able to do on S-plus graphsheet ( for those old enough to remember !)  it opened a multipagetabbed graphics devide that the user can easily navigate. ( we might think of a way to render it interactively inside Rstudio) versus running in in script.

**Comment by thomasp85** [comment]
That is fine with me🙂

**Comment by thomasp85** [comment]
But I would like to get a ping if you decide to make a separate package based on my code as hinted/suggested by @smouksassi

**Comment by dpastoor** [comment]
@smouksassi Yes, realistically there are a number of places this should probably be broken out into separate packages  - eg personally I think the control stream parsing and database creation could easily be a separate package.  

@thomasp85 thanks! @guiastrennec I am reflecting this in the contributors file for now, as well as at the top of the ggforce Rscript. Any other places you'd like to see it mentioned?

**Comment by guiastrennec** [comment]
@dpastoor we have given some thoughts about limiting the package dependencies by moving some of their code into `xpose` and we don't see this as the way to go forward for the following reasons:
1) **License**: we specifically chose the LGPL-3 license to allow the use of `xpose` in proprietary softwares without the "contamination effect" of the GPL-2 license. If GPL-2 code is added to `xpose` it needs to be clearly listed as such under the `LICENSE` file. Furthermore, that also means that the code licensed under GPL-2 would also have to be removed if `xpose` were to be used in proprietary software under a different license, likely resulting in errors on the remaining code.
2) **Maintenance**: moving extra code to `xpose` means that we would have to maintain it on the long run. We would also not automatically benefits from future updates made to the original code. We would also split the efforts in to separate packages. If the parmacometric community puts a lot of effort into the multiple page functionality, the benefits would not go back to the orginal code. However as mentioned by @smouksassi there is a need for a more general package handling multiples pages in `ggplot2`. Thus regarding the dependencies of `ggforce` of the R version requirements I suggest you upvote this [issue](https://github.com/thomasp85/ggforce/issues/55) to help @thomasp85 improve his package, which will then also benefit to more users.

@smouksassi we do not have currently the resources to develop a separate package for general use of multiple pages in `ggplot2`. I would instead encourage you to contribute to `ggforce` package. I had posted a detailed example [here](https://github.com/tidyverse/ggplot2/issues/86) how to generate multiple pages in a more general way. That should be a good start.

Finally, we realized that we did not provide any guidance for contributing to `xpose` and we apologize for that. We are now working on a `CONTRIBUTING.md` document and will try to release that ASAP.

**Comment by dpastoor** [comment]
@guiastrennec @andrewhooker @MikeKSmith and whoever else falls under the royal we - this is of course your choice as the funders/creators. I will leave with a couple comments that i hope you reconsider beyond the scope of this PR

1) As I mentioned in the issue raised, regardless of what you call a license, its what code that is included that you must also follow. My interactions with licensing and patent lawyers and going through due diligence has suggested that you will fall under that license already. If you intend to distribute in proprietary software you will still get hit with that. I would be beyond shocked if anyone pursued litigation, but you should think very carefully about that situation if you intend to think calling this LGPL will protect you in some way.

2) I disagree with this assertion that this will ease maintanence - there is a proverb in some programming languages, "a little copying is better than a lot of dependency." Ggforce is a big dependency as the heterogeneous nature pulls in a lot of other dependencies that are completely avoidable. Again, this is your choice, but I hope there is consideration to such issues going forward. To the issue you linked its not a problem with ggforce itself other requirements like sf that cause the 3.3 block so there is nothing to improve. If you need simple features for cartography that is the trade off. 

I think this is a wonderful package, and that it will thrive with community contributions and working with their requests. 

For now @mattfidler and any others ‘stuck’ on legacy clusters we will be maintaining a fork with support at astrazeneca/xpose over the next year until R 3.2 support is sunset.

**Comment by mattfidler** [comment]
Thank you @dpastoor for maintaining the fork.

**Pull request closed without merging**
